## **K-Nearest Neighbors (K-NN) Algorithm**

## What is K-NN?
K-Nearest Neighbors (K-NN) is a **supervised machine learning algorithm** used for both:

- **Classification** (predicting a category/class)
- **Regression** (predicting a numerical value)

K-NN works by finding the **K closest points** to a new data point and making a prediction based on those neighbors.


## Is K-NN classification or regression?
K-NN can be used for **both classification and regression**.

### ✅ K-NN Classification:
Predicts a class label (e.g., Cat/Dog, Spam/Not Spam).

### ✅ K-NN Regression:
Predicts a continuous value (e.g., house price, salary).


### **Steps of K-NN Algorithm**

### ✅ Step 1: Choose value of K
Select how many nearest neighbors you want to consider.

### ✅ Step 2: Calculate distance
Calculate the distance between the new point and all training points.

### ✅ Step 3: Select the K nearest neighbors
Sort distances and pick the K smallest.

### ✅ Step 4: Make Prediction
- **Classification:** Majority voting
- **Regression:** Average of K values


**✅ Euclidean Distance Formula (2D)**

If the dataset (training) point is $(x_1, y_1)$ and the new point is $(x_2, y_2)$, then the Euclidean distance between them is:

$$
d = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}
$$


**✅ Euclidean Distance for Multiple Features**

Suppose we have multiple dataset points:

$(x_1, y_1), (x_2, y_1), (x_3, y_1), ..., (x_n, y_1)$

and a new point:

$(x_{new}, y_{new})$

Then the distance between each dataset point $(x_i, y_i)$ and the new point is:

$$
d_i = \sqrt{(x_{new}-x_i)^2 + (y_{new}-y_i)^2}
$$

So we compute:

- $$d_1 = \sqrt{(x_{new}-x_1)^2 + (y_{new}-y_1)^2}$$
- $$d_2 = \sqrt{(x_{new}-x_2)^2 + (y_{new}-y_1)^2}$$
- $$d_3 = \sqrt{(x_{new}-x_3)^2 + (y_{new}-y_1)^2}$$
- ...
- $$d_n = \sqrt{(x_{new}-x_n)^2 + (y_{new}-y_1)^2}$$


# ✅ **K-NN Classification Example**

### ✅ Given Dataset Points:

| Point | Coordinates $(x_1, y_1)$ | Class |
|------|---------------------------|-------|
| A    | (2, 3)                   | Red   |
| B    | (4, 5)                   | Blue  |
| C    | (1, 2)                   | Red   |
| D    | (6, 7)                   | Blue  |

### ✅ New Point:
$(x_2, y_2) = (3,4)$

Choose:
$K = 3$

---

## ✅ Step 1: Calculate Euclidean Distance

Formula:

$$
d = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}
$$

### ✅ Distance from New Point (3,4) to each dataset point:

### Distance to A (2,3):
$$
d_A = \sqrt{(3-2)^2 + (4-3)^2}
     = \sqrt{1^2 + 1^2}
     = \sqrt{2}
     = 1.414
$$

### Distance to B (4,5):
$$
d_B = \sqrt{(3-4)^2 + (4-5)^2}
     = \sqrt{(-1)^2 + (-1)^2}
     = \sqrt{2}
     = 1.414
$$

### Distance to C (1,2):
$$
d_C = \sqrt{(3-1)^2 + (4-2)^2}
     = \sqrt{2^2 + 2^2}
     = \sqrt{8}
     = 2.828
$$

### Distance to D (6,7):
$$
d_D = \sqrt{(3-6)^2 + (4-7)^2}
     = \sqrt{(-3)^2 + (-3)^2}
     = \sqrt{18}
     = 4.243
$$

---

## ✅ Step 2: Sort distances (smallest first)

| Point | Distance | Class |
|------|----------|------|
| A | 1.414 | Red |
| B | 1.414 | Blue |
| C | 2.828 | Red |
| D | 4.243 | Blue |

---

## ✅ Step 3: Choose K = 3 nearest neighbors
Nearest neighbors are: A, B, C  
Classes: **Red, Blue, Red**

---

## ✅ Step 4: Majority Voting

Red = 2  
Blue = 1  

✅ Final Predicted Class:

$$
\hat{y} = \text{Red}
$$


# ✅ **K-NN Regression Example**

### ✅ Given Dataset Points:

| Point | Coordinates $(x_1, y_1)$ | Value $(y)$ |
|------|---------------------------|-------------|
| A    | (1, 2)                   | 10          |
| B    | (2, 3)                   | 20          |
| C    | (4, 5)                   | 40          |
| D    | (6, 7)                   | 60          |

### ✅ New Point:
$(x_2, y_2) = (3,4)$

Choose:
$K = 2$

---

## ✅ Step 1: Calculate Euclidean Distance

Formula:

$$
d = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}
$$

### Distance to A (1,2):
$$
d_A = \sqrt{(3-1)^2 + (4-2)^2}
     = \sqrt{2^2 + 2^2}
     = \sqrt{8}
     = 2.828
$$

### Distance to B (2,3):
$$
d_B = \sqrt{(3-2)^2 + (4-3)^2}
     = \sqrt{1^2 + 1^2}
     = \sqrt{2}
     = 1.414
$$

### Distance to C (4,5):
$$
d_C = \sqrt{(3-4)^2 + (4-5)^2}
     = \sqrt{(-1)^2 + (-1)^2}
     = \sqrt{2}
     = 1.414
$$

### Distance to D (6,7):
$$
d_D = \sqrt{(3-6)^2 + (4-7)^2}
     = \sqrt{(-3)^2 + (-3)^2}
     = \sqrt{18}
     = 4.243
$$

---

## ✅ Step 2: Sort distances (smallest first)

| Point | Distance | Value |
|------|----------|------|
| B | 1.414 | 20 |
| C | 1.414 | 40 |
| A | 2.828 | 10 |
| D | 4.243 | 60 |

---

## ✅ Step 3: Choose K = 2 nearest neighbors
Nearest neighbors: **B and C**  
Values: 20 and 40

---

## ✅ Step 4: Regression Prediction (Mean)

$$
\hat{y} = \frac{20 + 40}{2} = 30
$$

✅ Final Predicted Value:

$$
\hat{y} = 30
$$


In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix



In [ ]:
from sklearn.datasets import load_iris

iris = load_iris(as_frame=True)

# ✅ Select ONLY ONE FEATURE (choose any one)
X = iris.data[["petal length (cm)"]]
y = iris.target

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2
)

X_train.head()


,petal length (cm)
127,4.9
16,1.3
81,3.7
130,6.1
107,6.3


In [ ]:
print(type(iris))

<class 'sklearn.utils._bunch.Bunch'>


In [ ]:
numeric_features = X.columns
categorical_features = []   # Iris has no categorical columns


In [ ]:
# ✅ Numeric pipeline
numeric_pipeline = Pipeline(steps=[
    ("scaler", StandardScaler())
])

# ✅ Categorical pipeline
categorical_pipeline = Pipeline(steps=[
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])


In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_pipeline, numeric_features),
        ("cat", categorical_pipeline, categorical_features)
    ]
)


In [ ]:
knn_clf_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", KNeighborsClassifier(n_neighbors=5, metric="euclidean"))  # ✅ Euclidean
])

# Train model
knn_clf_pipeline.fit(X_train, y_train)

# Predict
y_pred = knn_clf_pipeline.predict(X_test)

# Evaluate
print("✅ Accuracy:", accuracy_score(y_test, y_pred))
print("\n✅ Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\n✅ Classification Report:\n", classification_report(y_test, y_pred))


✅ Accuracy: 0.9666666666666667

✅ Confusion Matrix:
 [[11  0  0]
 [ 0  9  1]
 [ 0  0  9]]

✅ Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.90      0.95        10
           2       0.90      1.00      0.95         9

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



# ✅ Macro Avg vs Weighted Avg

## ✅ Macro Average
Macro average gives **equal importance** to every class.
It is the **simple mean** of the scores of all classes.

### ✅ Formula:
$$
\text{Macro Avg} = \frac{\text{score}_0 + \text{score}_1 + \text{score}_2}{3}
$$

---

## ✅ Weighted Average
Weighted average gives importance based on **support** (number of samples in each class).
Classes with more samples contribute more.

### ✅ Formula:
$$
\text{Weighted Avg} =
\frac{(\text{score}_0 \cdot support_0) + (\text{score}_1 \cdot support_1) + (\text{score}_2 \cdot support_2)}
{support_0 + support_1 + support_2}
$$

---

# ✅ Example

Suppose we have 3 classes and their F1-scores are:

| Class | F1-score | Support |
|------|----------|---------|
| 0    | 1.00     | 50      |
| 1    | 0.80     | 30      |
| 2    | 0.60     | 20      |

Total samples:
$$
50 + 30 + 20 = 100
$$

---

## ✅ Macro Avg Calculation
$$
\text{Macro F1} = \frac{1.00 + 0.80 + 0.60}{3}
= \frac{2.40}{3}
= 0.80
$$

✅ Macro F1 = **0.80**

---

## ✅ Weighted Avg Calculation
$$
\text{Weighted F1} =
\frac{(1.00 \times 50) + (0.80 \times 30) + (0.60 \times 20)}{100}
$$

$$
= \frac{50 + 24 + 12}{100}
= \frac{86}{100}
= 0.86
$$

✅ Weighted F1 = **0.86**

---

# ✅ Final Difference
✅ **Macro Avg** treats all classes equally.  
✅ **Weighted Avg** gives more importance to classes with more data (higher support).  


# ✅ **How to Choose the Value of K in K-NN**

Choosing the value of **K** is very important because it affects the performance of KNN.

---

## ✅ 1) Effect of Small K
If **K is small** (e.g., K = 1 or 3):

✅ Model becomes very sensitive to noise  
✅ It may overfit the data  
✅ Decision boundary becomes irregular

📌 **Small K → Low Bias, High Variance (Overfitting)**

---

## ✅ 2) Effect of Large K
If **K is large** (e.g., K = 15 or 20):

✅ Model becomes more stable  
✅ But may ignore local patterns  
✅ It may underfit the data

📌 **Large K → High Bias, Low Variance (Underfitting)**

---

## ✅ 3) Best Way to Choose K (Cross Validation)
The best way to choose K is:

✅ Try different values of K  
✅ Check accuracy on validation/test data  
✅ Choose the K with maximum accuracy

---

## ✅ 4) Rule of Thumb
A common rule is:

$$
K \approx \sqrt{n}
$$

Where $n$ is the total number of training samples.

Example:  
If $n = 100$, then:

$$
K \approx \sqrt{100} = 10
$$

---

## ✅ 5) Prefer Odd Value of K (for Classification)
For binary classification, use **odd K** values like:

✅ K = 3, 5, 7, 9  

This avoids ties in majority voting.


# ✅ Limitations of K-NN Algorithm

Although KNN is simple and effective, it has some limitations:

---

## ✅ 1) Slow for Large Datasets
KNN calculates distance from the new point to **all training points**.

So prediction time is slow when dataset is large.

---

## ✅ 2) High Memory Usage
KNN stores the entire dataset because it does not train a model.

So it needs more memory for large data.

---

## ✅ 3) Sensitive to Feature Scaling
If features have different ranges (example: age vs salary),
distance calculation becomes incorrect.

✅ That is why **scaling (StandardScaler / MinMaxScaler)** is necessary.

---

## ✅ 4) Sensitive to Noise and Outliers
If the dataset has noisy points or outliers,
KNN predictions can become incorrect because it depends on nearest neighbors.

---


## ✅ 5) Choosing K is Difficult
There is no fixed best K for all datasets.

Different values of K give different results,
so we must tune K using validation.


# ✅ Regression Error Metrics (MAE, MSE)

When we use **KNN Regression**, we evaluate the model using error metrics.  
These metrics compare the **actual values** and **predicted values**.

Let:

- Actual values = $y_1, y_2, ..., y_n$
- Predicted values = $\hat{y}_1, \hat{y}_2, ..., \hat{y}_n$
- Number of samples = $n$

---

# ✅ 1) Mean Absolute Error (MAE)

## ✅ Definition:
MAE is the **average of the absolute differences** between actual and predicted values.

It shows how far predictions are from actual values (on average).

## ✅ Formula:
$$
MAE = \frac{1}{n}\sum_{i=1}^{n} |y_i - \hat{y}_i|
$$

## ✅ Advantages:
✅ Easy to understand (error is in same unit as data)  
✅ Less sensitive to outliers compared to MSE  


---

# ✅ 2) Mean Squared Error (MSE)

## ✅ Definition:
MSE is the **average of the squared differences** between actual and predicted values.

It gives more penalty to larger errors because errors are squared.

## ✅ Formula:
$$
MSE = \frac{1}{n}\sum_{i=1}^{n} (y_i - \hat{y}_i)^2
$$

## ✅ Advantages:
✅ Penalizes large errors heavily (good when large mistakes are serious)  


## ❌ Disadvantages:
❌ Very sensitive to outliers  


---



In [ ]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error

y_true = np.array([10, 20, 30, 40, 50])
y_pred = np.array([12, 18, 33, 37, 55])

mae = mean_absolute_error(y_true, y_pred)
mse = mean_squared_error(y_true, y_pred)


print("MAE =", mae)
print("MSE =", mse)



MAE = 3.0
MSE = 10.2
