## **Naive Bayes Algorithm**

## Naive Bayes?
**Naive Bayes** classifier, a **supervised machine learning algorithm** mainly used for:

- **Classification** (predicting a category/class)

Naive Bayes works by using **Bayes’ Theorem** to compute the probability of each class given the input features, and then choosing the class with the **highest probability**.


## Is Naive Bayes classification or regression?
Naive Bayes is used **mostly for classification**.

### Naive Bayes Classification:
Predicts a class label (e.g., Spam/Not Spam, Positive/Negative).

### Naive Bayes Regression:
Naive Bayes is **not typically used for regression** (predicting continuous values).


### **Steps of Naive Bayes Algorithm**

### Step 1: Calculate Prior Probability
Compute the probability of each class:
$$P(C)$$

### Step 2: Calculate Likelihood
Compute the probability of features given the class:
$$P(X|C)$$

### Step 3: Apply Bayes Theorem
Compute posterior probability:
$$P(C|X) = \frac{P(X|C)\,P(C)}{P(X)}$$

### Step 4: Predict
Choose the class with the highest posterior probability:



**Bayes Theorem Formula**

For a class $C$ and features $X$:

$$
P(C|X) = \frac{P(X|C)\,P(C)}{P(X)}
$$

Where:
- $P(C)$ = Prior probability of class  
- $P(X|C)$ = Likelihood of features given class  
- $P(X)$ = Evidence (normalizing constant)  
- $P(C|X)$ = Posterior probability


# **Naive Bayes Classification Example**

### Given Dataset (Text Classification):

| Message | Contains "Offer"? | Contains "Free"? | Class |
|--------|--------------------|------------------|-------|
| M1     | Yes                | Yes              | Spam  |
| M2     | Yes                | No               | Spam  |
| M3     | No                 | Yes              | Spam  |
| M4     | No                 | No               | Ham   |
| M5     | No                 | No               | Ham   |

### New Message:
Contains "Offer" = Yes, Contains "Free" = No

---

## Step 1: Prior
$$P(Spam)=\frac{3}{5}, \quad P(Ham)=\frac{2}{5}$$

## Step 2: Likelihood
$$P(Offer=Yes|Spam)=\frac{2}{3}, \; P(Free=No|Spam)=\frac{1}{3}$$
$$P(Offer=Yes|Ham)=\frac{0}{2}, \; P(Free=No|Ham)=\frac{2}{2}$$

## Step 3: Compare Posteriors (Proportional)
$$P(Spam|X) \propto \frac{3}{5}\cdot\frac{2}{3}\cdot\frac{1}{3}$$
$$P(Ham|X) \propto \frac{2}{5}\cdot 0 \cdot 1 = 0$$

Final Predicted Class: **Spam**


## Example: Why We Use Alpha (α) in Naive Bayes

We have this dataset:

| Message | Offer? | Free? | Class |
|--------|--------|-------|-------|
| M1 | Yes | Yes | Spam |
| M2 | Yes | No  | Spam |
| M3 | No  | Yes | Spam |
| M4 | No  | No  | Ham  |
| M5 | No  | No  | Ham  |

### Class counts
- Spam messages = 3  (M1, M2, M3)
- Ham messages  = 2  (M4, M5)

### Important observation
Word/feature **"Free=Yes" appears 0 times in Ham**  
So, without smoothing:

\[
P(\text{Free=Yes} \mid Ham) = \frac{0}{2} = 0
\]

This causes a big problem because Naive Bayes multiplies probabilities.

---

# Without Alpha (Problem)

If a new message contains **Free=Yes**, then:

\[
P(Ham \mid message) \propto P(Ham) \times 0 = 0
\]

So the model says:  
**"Ham is impossible"** just because "Free" never appeared in Ham in training data.

That is unrealistic in real life.

---

# With Alpha (α) = 1 (Laplace Smoothing)

Because our features are **binary (Yes/No)**, we use Bernoulli Naive Bayes smoothing:

\[
P(\text{feature=Yes} \mid class) =
\frac{count + \alpha}{N + 2\alpha}
\]

Where:
- count = how many times feature=Yes appears in that class
- N = total samples in that class
- 2 because the feature has 2 outcomes (Yes/No)
- α = smoothing value (usually 1)

---

## Calculate Probabilities with Alpha = 1

### 1) Free=Yes given Ham
- count = 0
- N = 2

\[
P(\text{Free=Yes} \mid Ham)=\frac{0+1}{2+2}= \frac{1}{4}=0.25
\]

Not zero anymore.

### 2) Free=Yes given Spam
- count = 2 (M1 and M3)
- N = 3

\[
P(\text{Free=Yes} \mid Spam)=\frac{2+1}{3+2}= \frac{3}{5}=0.60
\]

---

## Full Prediction Example (New Message)

Suppose new message has:
- Offer = Yes
- Free  = Yes

### Priors
\[
P(Spam)=\frac{3}{5}=0.6
\]
\[
P(Ham)=\frac{2}{5}=0.4
\]

Now compute Offer=Yes with alpha:

### Offer=Yes given Spam
count = 2, N=3

\[
P(\text{Offer=Yes} \mid Spam)=\frac{2+1}{3+2}=\frac{3}{5}=0.60
\]

### Offer=Yes given Ham
count = 0, N=2

\[
P(\text{Offer=Yes} \mid Ham)=\frac{0+1}{2+2}=\frac{1}{4}=0.25
\]

---

## Compute Scores

### Spam score:
\[
Score(Spam)=0.6 \times 0.60 \times 0.60 = 0.216
\]

### Ham score:
\[
Score(Ham)=0.4 \times 0.25 \times 0.25 = 0.025
\]

Since Spam score is bigger, the model predicts: **SPAM**



In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix



In [ ]:
from sklearn.datasets import load_iris

iris = load_iris(as_frame=True)

# ✅ Select ONLY ONE FEATURE (choose any one)
X = iris.data[["petal length (cm)"]]
y = iris.target

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2
)

X_train.head()


,petal length (cm)
97,4.3
98,3.0
31,1.5
99,4.1
109,6.1


In [ ]:
print(type(iris))

<class 'sklearn.utils._bunch.Bunch'>


In [ ]:
numeric_features = X.columns
categorical_features = []   # Iris has no categorical columns


In [ ]:
# ✅ Numeric pipeline
numeric_pipeline = Pipeline(steps=[
    ("scaler", StandardScaler())
])

# ✅ Categorical pipeline
categorical_pipeline = Pipeline(steps=[
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])


In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_pipeline, numeric_features),
        ("cat", categorical_pipeline, categorical_features)
    ]
)


In [ ]:
nb_clf_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", GaussianNB())  # ✅ Euclidean
])

# Train model
nb_clf_pipeline.fit(X_train, y_train)

# Predict
y_pred = nb_clf_pipeline.predict(X_test)

# Evaluate
print("✅ Accuracy:", accuracy_score(y_test, y_pred))
print("\n✅ Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\n✅ Classification Report:\n", classification_report(y_test, y_pred))


✅ Accuracy: 0.9

✅ Confusion Matrix:
 [[12  0  0]
 [ 0  8  0]
 [ 0  3  7]]

✅ Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.73      1.00      0.84         8
           2       1.00      0.70      0.82        10

    accuracy                           0.90        30
   macro avg       0.91      0.90      0.89        30
weighted avg       0.93      0.90      0.90        30



# **How to Choose a Naive Bayes Model / Settings**

Choosing the right Naive Bayes variant depends on your feature type.

---

## 1) Gaussian Naive Bayes (GaussianNB)
Use when features are **continuous numeric** (e.g., height, weight, petal length).

Assumes each feature follows a **normal (Gaussian) distribution** inside each class.

---

## 2) Multinomial Naive Bayes (MultinomialNB)
Use when features are **counts/frequencies** (e.g., bag-of-words word counts in NLP).

---

## 3) Bernoulli Naive Bayes (BernoulliNB)
Use when features are **binary** (0/1), such as "word present or not".

---

## 4) Smoothing (Laplace / Alpha)
To avoid zero probabilities, we apply smoothing:

Common choice: $\alpha = 1$ (Laplace smoothing)  
Try different values using validation for best performance.


# Limitations of Naive Bayes Algorithm

Although Naive Bayes is fast and effective, it has some limitations:

---

## 1) Strong Independence Assumption
It assumes features are independent given the class, which is often not true in real data.

---

## 2) Can Underperform with Correlated Features
When features are highly correlated, Naive Bayes may give weaker accuracy.

---

## 3) Zero-Probability Problem (Without Smoothing)
If a feature value never appears in training for a class, likelihood can become 0.
Smoothing helps solve this.

---

## 4) Simple Decision Boundary
Naive Bayes is a relatively simple model and may not capture complex patterns.
